services:
  db:
    image: mariadb:11
    container_name: ideas_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ideas_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./ideas-api
    container_name: ideas-api
    restart: always
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: ideas_db
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./ideas-web
    container_name: ideas-web
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  db_data: